### ISSUE TITLE
[Examples] DocType Builder

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#39]
- [x] A "view" editor showing the first to Nth levels of navigation inside a collapsible fieldset - made with a mix of ATable and AForm (#36)
- [x] A table for the Hooks inside a collapsible fieldset (#36)
- [x] An XState FSM editor component inside a collapsible fieldset (#37)
- [x] A code editor, that can convert those primitives above but allow you to write a Vue component in the DocType builder, inside a collapsible fieldset (#38)
- [ ] Since this all get pushed to MirageJS, we should be able to link and preview in a separate tab 
- [ ] "Export" side effect hook to persist config as JSON
